//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeiraProfissões.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a4c265_feira19Entities : DbContext
    {
        public db_a4c265_feira19Entities()
            : base("name=db_a4c265_feira19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_avaliacao> tb_avaliacao { get; set; }
        public virtual DbSet<tb_log_navegacao> tb_log_navegacao { get; set; }
    }
}
