//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeiraProfissões.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_avaliacao
    {
        public int id_avaliacao { get; set; }
        public int qt_estrelas { get; set; }
        public Nullable<System.DateTime> dt_avaliacao { get; set; }
        public string ip_address { get; set; }
    }
}
