//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeiraProfissões.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_navegacao
    {
        public int id_log { get; set; }
        public Nullable<System.DateTime> dt_log { get; set; }
        public string nm_page { get; set; }
        public string ip_address { get; set; }
    }
}
